### ISSUE TITLE
智慧平台简介

### ISSUE THREAD

**Issue by feichangshun** [bjtrrc/trrc_101#1]
# 智慧平台：北京天润融创公司开发的智慧平台产品。

   **产品url**：[http://101.200.184.21:8080/socketServer/socketWeb/html/index_taishi.html](url)
**包括技术**：_gis_、通讯、视频、态势等技术。
- gis
- 通讯
- 视频
- 态势

**Comment by trrcFeichangshun** [comment]
完成
