### ISSUE TITLE
视频监控

### ISSUE THREAD

**Issue by trrcFeichangshun** [bjtrrc/trrc_101#3]
1、测试捷视飞通接口，演示视频调度各个模块的功能。
2、需求分析。
3、设计音视频融合系统的整体开发系统架构。评估项目工作量。编排具体的开发计划。
4、分析和理解每个视频接口的调用逻辑和使用方法，学会正确使用接口实现特定的功能。
5、按照系统设计图，对每个视频模块进行独立开发。
6、参考已有的语音客户端，开发语音模块功能。
7、参考市场上主流的音视频系统的布局和功能，集成语音和视频服务。
8、攻克整个系统的难点和问题点。
9、系统测试。
10、根据客户的反馈和意见，调整软件的功能和布局。
11、在实现软件基本功能、解决软件bug的前提下，出第一个版本。
12、对系统做进一步改进和完善。

**Comment by trrcLiuwei** [comment]
说明：目前还没看到捷飞视频的每个接口的运行效果图，不清楚视频的具体功能和实现难度，无法评估工作量。待演示运行后，作出工作量的评估，会补上具体的研发进度安排。
